### PR TITLE
Feature/sienna

### PR DESCRIPTION
**Pull request by misssn1998**
Change README file

### CODE REVIEW

**Review by Kinzi-c — COMMENTED** [review]
Hi Sienna,
Can you please add you speciality next to your name. For example: Front-end Back-end Design or Architecture
You can add multiple if you'd like

**Comment by misssn1998** [comment]
> Hi Sienna, Can you please add you speciality next to your name. For example: Front-end Back-end Design or Architecture You can add multiple if you'd like

Hi Kinji, I just update it

**Review by Kinzi-c — CHANGES_REQUESTED** [review]
Can you please pull the latest main onto your branch? there have been changes since you first created your branch.

**Review by Kinzi-c — APPROVED** [review]

**Review by Kinzi-c — APPROVED** [review]
Great job Sienna!

**Pull request merged**
